geostyler/geostyler-cli

.eslintrc.js, package.json, src/index.ts, src/logHelper.ts
=> Enhanced eslint configuration and fixing of reported errors

src/logHelper.ts
=> Fix a typo

README.md, package.json
=> Rename binary to geostyler and enhance README

src/index.ts, src/logHelper.ts, tsconfig.json
=> Add -v/--version option

package.json
Use the latest version of geostyler-mapfile-parser
=> Update geostyler-mapfile-parser to v0.0.3

package-lock.json, package.json
=> Clean up before building

README.md
Trivial, I'll merge directly after opening.
=> Add missing backtick to README.md

README.md
Trivial, see #14, this time for another option. 
I will again merge immediately.
=> Add another missing backtick to README.md

.eslintrc.js, .github/dependabot.yml, package-lock.json, package.json
- updates several dependencies
- make use of @terrestris/eslint-config-typescript
- adds dependabot.yml
=> updates dependecies

package-lock.json, package.json, src/index.ts, tsconfig.json
This updates several packages and downgrades ora.
It also adapts the code to be more strictly typed.
=> updates several packages

src/index.ts
=> Avoid error when no file extension found

.vscode/launch.json, .vscode/tasks.json, package-lock.json, package.json, src/index.ts
This updates all parsers to their latest versions. This includes the syntax change of `geostyler-style`.
It also updates the dependencies to their latest versions (where possible).
=> Parser updates

README.md
=> Add info about se option to README

.github/workflows/on-pull-request.yml, .github/workflows/on-push-master.yml, package.json, src/index.ts, test.js, testdata/point_simplepoint.geostyler, testdata/point_simplepoint.map
Currently testing on all branches but can revert to master following a review. 
This adds a GHA to build the client and run a few test examples from the command line. It then does a simple check to see that the file was created.
=> Add workflow and command line tests

.github/workflows/release.yml
=> ci: replace RELEASE_TOKEN with GH_RELEASE_TOKEN

.github/workflows/commitlint.yml, package-lock.json, package.json
This adds the commitlint and semantic-release dependencies as well as a pipeline for commitlint
=> Commitlint dependencies

.github/workflows/notify-discord.yml, package-lock.json, package.json
=> chore(deps): remove unused package np

.github/workflows/release.yml, package.json
=> fix: ensure published assets have correct version

.gitignore, package-lock.json, package.json, src/index.ts, test.js, testdata/test.lyrx
This adds the geostyler-lyrx-parser as potential sourceParser.
=> Add geostyler-lyrx-parser

README.md, package-lock.json, package.json, src/index.ts, src/logHelper.ts, test.js, testdata/olFlatStyles/point_simple.json
This adds the openlayers flatstyle parser.
=> Ol flat style parser
